deployment:
  name: greeting-app-deployment
  replicaCount: 1
  image:
    app: greeting-app
    version: 1.1-SNAPSHOT
    pullPolicy: IfNotPresent

service:
  name: greeting-app-service
  type: NodePort
  port: 8081
  targetPort: 8080
  nodePort: 31234

appConfig:
  appName: greeting-app
